# [√]需要手动修改 [-]不推荐修改 [※]可选项，不影响系统运行

# ===================================================
# [√] 账号信息
# ---------------------------------------------------
# Tips：使用脚手架检测连接 python main.py ping
# ===================================================
EMAIL: ""
PASSWORD: ""

# ===================================================
# [√※] 通信鸽
# ---------------------------------------------------
# 一些主流的通信接口，用于反射运行报告
# Docs https://github.com/caronc/apprise
# ===================================================
message_pusher_settings:
  enable: true
  pusher:
    PUSHER_EMAIL: ""
    PUSHER_DINGTALK: ""
    PUSHER_TELEGRAM: ""
    PUSHER_SERVERCHAN: ""
    PUSHER_DISCORD: ""

# ===================================================
# [※] LOCALIZED LANGUAGE
# ---------------------------------------------------
#  https://en.wikipedia.org/wiki/List_of_ISO_639-1_codes
# [zh en ru fr ja ko de ...]
# ===================================================
LOCALE_LANG: "zh"

# ===================================================
# [-※] 定时任务配置
# ---------------------------------------------------
# explorer        |探索者，审查每周免费游戏
# bricklayer      |搬瓦工，为用户获取免费游戏
# ---------------------------------------------------
# interval      |任务间隔，单位秒
# Default: interval--(explorer)--3600s
# Default: interval--(bricklayer)--86400s
# ---------------------------------------------------
# Tips: 手动修改的 interval 不可小于默认值
# ===================================================
scheduler:
  explorer:
    enable: true
    interval: 3600
  bricklayer:
    enable: true
    interval: 86400
